-- Supabase Setup SQL
-- Generated at: 5/11/2026, 12:20:56 AM


-- From 00_storage.sql
-- Storage bucket for lost items
INSERT INTO storage.buckets (id, name, public)
VALUES ('lost-items', 'lost-items', true)
ON CONFLICT (id) DO NOTHING;

-- From 01_schema.sql
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Booth (Realtime Status)
CREATE TABLE IF NOT EXISTS stalls_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stall_name TEXT UNIQUE NOT NULL,
    crowd_level INTEGER DEFAULT 0,
    stock_level INTEGER DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- News
CREATE TABLE IF NOT EXISTS news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    edit_reason TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Lost
CREATE TABLE IF NOT EXISTS lost_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    place TEXT NOT NULL,
    edit_reason TEXT,
    photo_path TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- QA
CREATE TABLE IF NOT EXISTS questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text TEXT NOT NULL,
    answer TEXT,
    edit_reason TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Server config
CREATE TABLE IF NOT EXISTS app_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    value_int INTEGER,
    value_text TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Vote targets
CREATE TABLE IF NOT EXISTS vote_targets (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Vote data
CREATE TABLE IF NOT EXISTS votes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    voter_id TEXT NOT NULL,
    target_id TEXT REFERENCES vote_targets(id) ON DELETE CASCADE,
    category TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    UNIQUE(voter_id, category)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_stalls_name ON stalls_status(stall_name);
CREATE INDEX IF NOT EXISTS idx_news_created_at ON news(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_app_settings_key ON app_settings(key);
CREATE INDEX IF NOT EXISTS idx_votes_voter_category ON votes(voter_id, category);

-- From 02_functions.sql
-- Get all data
CREATE OR REPLACE FUNCTION get_all_data()
RETURNS json AS $$
DECLARE
  result json;
BEGIN
  SELECT json_build_object(
    's', (SELECT COALESCE(json_agg(json_build_object('i', id, 'c', crowd_level, 'l', stock_level)), '[]'::json) FROM stalls_status),
    'n', (SELECT COALESCE(json_agg(json_build_object('i', id, 't', title, 'c', content, 'a', to_char(created_at AT TIME ZONE 'Asia/Tokyo', 'MMDDHH24MI'), 'r', edit_reason)), '[]'::json) FROM (SELECT * FROM news ORDER BY created_at DESC LIMIT 5) as news),
    'l', (SELECT COALESCE(json_agg(json_build_object('i', id, 'n', name, 'p', place, 'a', to_char(created_at AT TIME ZONE 'Asia/Tokyo', 'MMDDHH24MI'), 'r', edit_reason, 'f', photo_path)), '[]'::json) FROM (SELECT * FROM lost_items ORDER BY created_at DESC LIMIT 10) as lost_items),
    'q', (SELECT COALESCE(json_agg(json_build_object('i', id, 't', text, 'w', answer, 'a', to_char(created_at AT TIME ZONE 'Asia/Tokyo', 'MMDDHH24MI'), 'r', edit_reason)), '[]'::json) FROM (SELECT * FROM questions ORDER BY created_at DESC LIMIT 20) as questions),
    'config', (SELECT COALESCE(json_object_agg(key, value_int), '{}'::json) FROM app_settings)
  ) INTO result;
  RETURN result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Get booth data
CREATE OR REPLACE FUNCTION get_stalls_only()
RETURNS json AS $$
DECLARE
  result json;
BEGIN
  SELECT json_build_object(
    's', (SELECT COALESCE(json_agg(json_build_object('i', id, 'c', crowd_level, 'l', stock_level)), '[]'::json) FROM stalls_status)
  ) INTO result;
  RETURN result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Vote RPC
CREATE OR REPLACE FUNCTION vote_for_target(
    p_voter_id TEXT,
    p_target_id TEXT,
    p_category TEXT
) RETURNS VOID AS $$
DECLARE
    v_start_at INT;
    v_end_at INT;
    v_voting_enabled INT;
    v_now INT;
    v_client_ip TEXT;
    v_last_vote_time TIMESTAMPTZ;
BEGIN
    SELECT value_int INTO v_start_at FROM app_settings WHERE key = 'vote_start_at';
    SELECT value_int INTO v_end_at FROM app_settings WHERE key = 'vote_end_at';
    SELECT value_int INTO v_voting_enabled FROM app_settings WHERE key = 'voting_enabled';
    v_now := EXTRACT(EPOCH FROM now())::INT;

    -- T1: Time & Enable check
    IF v_voting_enabled IS NULL OR v_voting_enabled <> 1 THEN
        RAISE EXCEPTION '投票は現在受け付けておりません';
    END IF;
    IF v_start_at IS NULL OR v_end_at IS NULL THEN
        RAISE EXCEPTION '投票設定が見つかりません';
    END IF;
    IF v_now < v_start_at OR v_now > v_end_at THEN
        RAISE EXCEPTION '投票期間外です';
    END IF;

    -- T4: Existence check
    IF NOT EXISTS (SELECT 1 FROM vote_targets WHERE id = p_target_id AND category = p_category) THEN
        RAISE EXCEPTION '無効な投票先です';
    END IF;

    -- T3: IP-based Rate Limit
    v_client_ip := current_setting('request.headers', true)::json->>'x-forwarded-for';
    IF v_client_ip IS NULL THEN v_client_ip := p_voter_id; END IF;

    SELECT MAX(created_at) INTO v_last_vote_time FROM votes WHERE voter_id = v_client_ip;
    IF v_last_vote_time IS NOT NULL AND (now() - v_last_vote_time) < interval '5 seconds' THEN
        RAISE EXCEPTION '連打は禁止されています。数秒後に再試行してください。';
    END IF;

    -- Vote execution
    DELETE FROM votes WHERE voter_id = v_client_ip AND category = p_category;
    INSERT INTO votes (voter_id, target_id, category)
    VALUES (v_client_ip, p_target_id, p_category);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Vote time synchronization (T4)
CREATE OR REPLACE FUNCTION fn_sync_app_settings_time()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.value_text IS NOT NULL AND NEW.value_text <> '' THEN
        IF NEW.value_text ~ '^\d{4}-\d{2}-\d{2}' THEN
            BEGIN
                NEW.value_int := EXTRACT(EPOCH FROM NEW.value_text::timestamptz)::int;
            EXCEPTION WHEN OTHERS THEN
                RAISE EXCEPTION 'Date convertion error: %', NEW.value_text;
            END;
        ELSE
            RAISE EXCEPTION 'Invalid date format (YYYY-MM-DD): %', NEW.value_text;
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_sync_app_settings_time ON app_settings;
CREATE TRIGGER tr_sync_app_settings_time
BEFORE INSERT OR UPDATE ON app_settings
FOR EACH ROW
EXECUTE FUNCTION fn_sync_app_settings_time();

-- Vote results view
DROP VIEW IF EXISTS vote_results CASCADE;
CREATE VIEW vote_results
WITH (security_invoker = true)
AS
SELECT
    vt.id,
    vt.category,
    COUNT(vo.id) as vote_count
FROM vote_targets vt
LEFT JOIN votes vo ON vt.id = vo.target_id
GROUP BY vt.id, vt.category, vt.display_order
ORDER BY vt.category, vote_count DESC, vt.display_order;

-- Vote results
CREATE OR REPLACE FUNCTION get_vote_results_compressed()
RETURNS json AS $$
BEGIN
  RETURN (
    SELECT json_agg(json_build_object(
      'c', category,
      'i', id,
      'v', vote_count
    ))
    FROM vote_results
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- From 03_security.sql
-- Enable RLS
ALTER TABLE stalls_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE news ENABLE ROW LEVEL SECURITY;
ALTER TABLE lost_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE vote_targets ENABLE ROW LEVEL SECURITY;
ALTER TABLE votes ENABLE ROW LEVEL SECURITY;

-- Read (all users)
CREATE POLICY "Allow Public Read Stalls" ON stalls_status FOR SELECT USING (true);
CREATE POLICY "Allow Public Read News" ON news FOR SELECT USING (true);
CREATE POLICY "Allow Public Read LostItems" ON lost_items FOR SELECT USING (true);
CREATE POLICY "Allow Public Read Questions" ON questions FOR SELECT USING (true);
CREATE POLICY "Allow Public Read Settings" ON app_settings FOR SELECT USING (true);
CREATE POLICY "Allow Public Read VoteTargets" ON vote_targets FOR SELECT USING (true);

-- Insert (user for QA)
CREATE POLICY "Allow Public Insert Questions" ON questions FOR INSERT WITH CHECK (true);

-- Write (admin/stall-admin)
CREATE POLICY "Allow Admin Update Stalls" ON stalls_status FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

-- Write (admin for news/lost items)
CREATE POLICY "Allow Admin Full News" ON news FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow Admin Full LostItems" ON lost_items FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Write / Delete (admin for Q&A)
CREATE POLICY "Allow Admin Manage Questions" ON questions FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow Admin Delete Questions" ON questions FOR DELETE TO authenticated USING (true);

-- Write (admin for server config / vote)
-- T4: Restricted to authenticated users
CREATE POLICY "Allow Admin Update Settings" ON app_settings FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow Admin Full Settings" ON app_settings FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow Admin Manage VoteTargets" ON vote_targets FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Security: Explicitly block anonymous updates to app_settings (T4)
CREATE OR REPLACE FUNCTION fn_block_anon_update()
RETURNS TRIGGER AS $$
BEGIN
    IF auth.role() = 'anon' THEN
        RAISE EXCEPTION 'Security Violation:';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS tr_block_anon_update ON app_settings;
CREATE TRIGGER tr_block_anon_update BEFORE UPDATE ON app_settings
FOR EACH ROW EXECUTE FUNCTION fn_block_anon_update();

-- Read (admin for vote)
CREATE POLICY "Allow Admin Read Votes" ON votes FOR SELECT TO authenticated USING (true);

-- Lost images storage
CREATE POLICY "Allow authenticated users to upload lost items"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'lost-items');

CREATE POLICY "Allow authenticated users to select lost items"
ON storage.objects FOR SELECT
TO authenticated
USING (bucket_id = 'lost-items');

CREATE POLICY "Allow authenticated users to update lost items"
ON storage.objects FOR UPDATE
TO authenticated
USING (bucket_id = 'lost-items');

CREATE POLICY "Allow authenticated users to delete lost items"
ON storage.objects FOR DELETE
TO authenticated
USING (bucket_id = 'lost-items');

-- From 04_seed_data.sql
-- Server Configuration (Static Settings)
INSERT INTO app_settings (key, value_int, value_text) VALUES
('maintenance_mode', 0, NULL),
('voting_enabled', 1, NULL),
('vote_start_at', 0, '2026-05-23 10:00:00+09'),
('vote_end_at', 0, '2026-05-24 14:00:00+09'),
('poll_interval_ms', 30000, NULL)
ON CONFLICT (key) DO UPDATE SET
    value_text = EXCLUDED.value_text,
    value_int = CASE 
        WHEN EXCLUDED.value_text IS NOT NULL THEN app_settings.value_int
        ELSE EXCLUDED.value_int 
    END;


-- From 05_realtime.sql
-- Realtime
BEGIN;
  DROP PUBLICATION IF EXISTS supabase_realtime;
  CREATE PUBLICATION supabase_realtime FOR TABLE stalls_status, news;
COMMIT;

ALTER TABLE stalls_status REPLICA IDENTITY FULL;
ALTER TABLE news REPLICA IDENTITY FULL;


-- From 06_generate_votejson.sql
-- vote_targets -> vote.json
-- Copy the output to vote.json
SELECT json_agg(
    json_build_object(
        'id', id,
        'name', name,
        'category', category
    ) ORDER BY category, display_order
)
FROM vote_targets;

-- JSON Data (Auto-generated from booth.json and exhibitions.json)
-- Stalls Status (Master Names)
INSERT INTO stalls_status (id, stall_name) VALUES (1, 'ポップコーン'), (2, 'チュロス'), (3, 'たこ焼き'), (4, '焼き鳥')
ON CONFLICT (id) DO UPDATE SET stall_name = EXCLUDED.stall_name;

-- Reset stalls_status sequence (suppressing output)
DO $$
BEGIN
  PERFORM setval(pg_get_serial_sequence('stalls_status', 'id'), COALESCE(MAX(id), 1)) FROM stalls_status;
END $$;

-- Vote Targets (Booths)
INSERT INTO vote_targets (id, name, category, display_order) VALUES ('01', 'ポップコーン', 's', 1), ('02', 'チュロス', 's', 2), ('03', 'たこ焼き', 's', 3), ('04', '焼き鳥', 's', 4)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, display_order = EXCLUDED.display_order;

-- Vote Targets (Exhibitions)
INSERT INTO vote_targets (id, name, category, display_order) VALUES ('31', '写真展示', 'e', 1), ('32', 'フォトスポット', 'e', 2), ('33', '学科展示', 'e', 3), ('34', 'ロボット展示', 'e', 4)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, display_order = EXCLUDED.display_order;

